[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Rewrite API calls to Netlify Functions (pass parameters via query string)
[[redirects]]
  from = "/api/reddit/subreddit/:subreddit"
  to = "/.netlify/functions/reddit-subreddit?subreddit=:subreddit"
  status = 200
  force = true

[[redirects]]
  from = "/api/reddit/posts/:subreddit"
  to = "/.netlify/functions/reddit-posts?subreddit=:subreddit"
  status = 200
  force = true

[[redirects]]
  from = "/api/steam/appdetails/:appid"
  to = "/.netlify/functions/steam-appdetails?appid=:appid"
  status = 200
  force = true

[[redirects]]
  from = "/api/steamspy/appdetails/:appid"
  to = "/.netlify/functions/steamspy-appdetails?appid=:appid"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
